# Generated by Django 3.2.5 on 2022-02-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rating',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
