# Generated by Django 3.2.5 on 2022-02-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_entry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
